name: firebase_authentication_tutorial
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  splashscreen: ^1.3.5
  flutter_launcher_icons: "^0.8.0"
  flutter_launcher_name: "^0.0.1"
  cupertino_icons: ^0.1.3

  #Firebase
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0+1

  provider: ^4.3.2+1



flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/1.png"
flutter_launcher_name:
  name: "Vishnu app"



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/1.png
